name: Update Gist

on:
  push:
    branches: master

  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - name: Install
        # run: npm ci
      - name: Update gist
        uses: qianxi0410/waka-box@master
        # run: node ./index.js
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 938b1c78b2e72d84aa819e1510a37b37
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
